name: costly
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  image: ^4.5.4
  intl: ^0.20.2
  open_file: ^3.5.10
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.1
  printing: ^5.14.2
  provider: ^6.1.5+1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
